### ISSUE TITLE
Refactor bash scripts to Swift-FP using Bow

### ISSUE THREAD

**Issue by miguelangel-dev** [bow-swift/nef#112]
To reduce the legacy code and make it more stable, we need to migrate the whole bash-scripts to Swift in purely functional programming.

We need to migrate the next scripts:
- [x] nef (presenting menus + version option) (close: #127) [**tracked in #126 , #129**]
- [x] nef-clean (clean up nef Playground) [**tracked in #128**]
- [x] nef-playground  [fix bug: #121] [**tracked in #125**]
- [x] nefc (compiler) [fix bug: #122] [**tracked in #124**]
- [x] nef-carbon [**tracked in #118**]
- [x] nef-jekyll [**tracked in #113, #117**]
- [x] nef-markdown [**tracked in #108, #115**]
- [x] nef-jekyll-page [**tracked in #107, #113**]
- [x] nef-markdown-page [**tracked in #107, #108**]
- [x] nef-common [**tracked in #109, #110**]

After the refactor, we will find the whole code in the Xcode project `nef > project > nef.xcodeproj` and it will be divided into 4 layers:
- `UI` it'll contain the new CLI swift-FP scripts.
- `Component` the whole frameworks under the `nef` umbrella. It will provide the entire business-logic for nef and let to devs import in their projects, to use the API directly.
- `Core` to parser/create/render AST from Xcode Playgrounds. It interprets the raw Xcode Playground page.
- `Tests` when the whole code will be in Swift, it will be accessible to testing and reduce the regression between each release.
