### ISSUE TITLE
nef modularization - open API

### ISSUE THREAD

**Issue by miguelangel-dev** [bow-swift/nef#78]
## Description
We want to open `nef` to developers. On this way, `nef` should be easily imported into Xcode projects to expand its power. 

## Goal
Then we could take advantage of these renders in any other external Xcode project.

## Proposal
We want to modularize `nef` - so internal Core does not depend on CLI. We need to extract the whole renders and isolate in a Cored module; moreover, we need to create a `Component` framework to open API to developers so they can use the main nef's features:

- Generate Jekyll microsite.
- Generates Markdown files.
- Export Carbon snippets from code selection.

## How will it be developed?
`nef` project should be modularized as follow:
- `UI`: module with the CLI dependencies
- `Componentes`: public modules to be imported in your macOS project. It is the open API to nef.
- `Core`: private modules where analysis syntax, lexical and rendered will happen.

## Roadmap
- [x] Modularize `nef` (tracked in https://github.com/bow-swift/nef/pull/80)
- [x] Open API for Carbon (tracked in https://github.com/bow-swift/nef/pull/80)
- [x] Open API for Jekyll (tracked in https://github.com/bow-swift/nef/pull/82)
- [x] Open API for Markdonw (tracked in https://github.com/bow-swift/nef/pull/81)
